---
title: "Visualization_ggplot_1"
author: "Annie Yu"
date: "9/27/2018"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

```{r}
library(tidyverse)
library(ggridges)
```


```{r data_import, cache=TRUE}
library(rnoaa)

weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```

## Start to make the plot

Blank plot.....

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))
```

Scatterplot...
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))+
  geom_point()
```

```{r}
weather_df %>%
  filter(name == "CentralPank_NY") %>%
  ggplot(aes(x = tmin, y = tmax))+
  geom_point()
```

```{r}
weather_sp =
 ggplot(weather_df, aes(x = tmin, y = tmax))+
  geom_point()
```

## More plot  options

Add on aesthetic

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))+
  geom_point(aes(color = name))
```


Add a geom
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))+
  geom_point(aes(color = name))+
  geom_smooth(se = FALSE)
```

Add some options.....

add a gemo

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))+
  geom_point(aes(color = name), alpha = 0.4)+
  geom_smooth(se = FALSE)
```

move color code to ggplot from the geom_point

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax,color = name))+
  geom_point(alpha = 0.4)+
  geom_smooth(se = FALSE)
```

Factting.....(divide 3 form)

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax,color = name))+
  geom_point(alpha = 0.4)+
  geom_smooth(se = FALSE)+
  facet_grid( ~ name)
```

NO color ....
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))+
  geom_point(alpha = 0.4)+
  geom_smooth(se = FALSE)+
  facet_grid( ~ name)
```


A more interesting plot

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) +
  geom_point()
```


```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) +
  geom_line()
```


```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name, size = prcp)) +
  geom_point()
```


```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name, size = prcp)) +
  geom_point()+
  geom_smooth(se = FALSE) +
  facet_grid( ~ name)

```

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name, size = prcp)) +
  geom_smooth(se = FALSE)
```


```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name, size = prcp)) +
  geom_hex()
```

```{r}
ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin), color = "blue")
ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin, color = "blue"))
```


## Univariable plot

Histrogram!

```{r}
ggplot(weather_df, aes(x = tmax)) +
  geom_histogram()
```

```{r}
ggplot(weather_df, aes(x = tmax)) +
  geom_histogram() +
  facet_grid(~name)
```

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) +
  geom_histogram()
```


Density plot...

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) +
  geom_density(alpha=0.5)
```

Boxplots!!
```{r}
ggplot(weather_df, aes(x = name, y = tmax)) +
  geom_boxplot()
```

Violin plot...
```{r}
ggplot(weather_df, aes(x = name, y = tmax)) +
  geom_violin()
```

Ridge plot...
```{r}
ggplot(weather_df, aes(x = tmax, y = name)) +
  geom_density_ridges()
```

```{r}
ggplot(weather_df, aes(x = prcp, y = name)) + 
  geom_density_ridges(scale = .85)
```

## Save the ggplot

```{r}
weather_plot = ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) 

ggsave("weather_plot.pdf", weather_plot, width = 8, height = 5)
```

